# Generated by Django 4.2.4 on 2023-10-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_register_remove_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
