# Generated by Django 4.2.4 on 2023-10-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_delete_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
