# Generated by Django 4.2.4 on 2023-10-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='register',
            table='Register',
        ),
    ]
