# Generated by Django 4.2.4 on 2023-10-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_alter_contact_table_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='Customer',
        ),
    ]
