# Generated by Django 4.2.4 on 2023-11-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conventionhall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(default=0, upload_to='')),
                ('address', models.CharField(max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_number', models.BigIntegerField()),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('cost', models.BigIntegerField()),
                ('amenities', models.TextField()),
                ('seating_capacity', models.CharField(max_length=30)),
                ('rooms_available', models.BigIntegerField()),
                ('catering', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Conventionhall',
            },
        ),
    ]
