# Generated by Django 4.2.4 on 2023-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_conventionhall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conventionhall',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conventionhall',
            name='rooms_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='conventionhall',
            name='seating_capacity',
            field=models.IntegerField(),
        ),
    ]
