# Generated by Django 4.2.4 on 2023-11-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0014_rating_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='hall',
            new_name='conventionhall',
        ),
    ]
