# Generated by Django 4.2.4 on 2023-11-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0016_remove_rating_conventionhall_rating_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='mail',
        ),
        migrations.AddField(
            model_name='rating',
            name='conventionhall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotelapp.conventionhall'),
            preserve_default=False,
        ),
    ]
