# Generated by Django 4.2.4 on 2023-11-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0017_remove_rating_mail_rating_conventionhall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='conventionhall',
        ),
    ]
