# Generated by Django 4.2.4 on 2023-12-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0019_rating_conventionhall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('required_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('no_of_guests', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('conventionhall1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.conventionhall')),
                ('conventionhall2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventionhall2', to='hotelapp.conventionhall')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
