# Generated by Django 4.2.4 on 2023-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0020_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='conventionhall2',
        ),
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='new', max_length=30),
        ),
    ]
