# Generated by Django 4.2.4 on 2023-12-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0021_remove_booking_conventionhall2_booking_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
