# Generated by Django 4.2.4 on 2023-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0022_alter_booking_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
